import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { Badge, Button, Card, Empty, Field } from '../components/ui';
import { createClassEvent, deleteClassEvent, listAllClassEvents, listCrossClassSchedules, listAllAssignments, listClasses, updateClassEvent } from '../lib/repository';
import type { Assignment, ClassEvent, ClassEventType, ClassRecord, Schedule } from '../types/models';
import { hasCapability } from '../lib/permissions';
import { getClassPosition } from '../lib/repository';
import { getActiveClassId, openClassModule, setActiveClassId } from '../lib/router';
import { showToast } from '../components/ToastHost';
import { requestConfirm } from '../components/DialogHost';

const days=['','Senin','Selasa','Rabu','Kamis','Jumat','Sabtu','Minggu'];
const typeLabel:Record<ClassEventType,string>={class:'Kegiatan',presentation:'Presentasi',exam:'Ujian',meeting:'Rapat',task_deadline:'Deadline tugas',other:'Event'};
const typeIcon:Record<ClassEventType,string>={class:'📘',presentation:'🎤',exam:'📝',meeting:'👥',task_deadline:'⏰',other:'📌'};

export function CalendarPage(){
 const [items,setItems]=useState<Schedule[]>([]),[events,setEvents]=useState<ClassEvent[]>([]),[tasks,setTasks]=useState<Assignment[]>([]),[classes,setClasses]=useState<ClassRecord[]>([]);
 const [day,setDay]=useState('all'),[error,setError]=useState(''),[filter,setFilter]=useState<'all'|'schedule'|'event'|'task'>('all');
 const [canManage,setCanManage]=useState(false),[activeClass,setActiveClass]=useState('');
 const [manageByClass,setManageByClass]=useState<Record<string,boolean>>({});
 const [selectedDate,setSelectedDate]=useState(()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`});
 const [form,setForm]=useState({type:'presentation' as ClassEventType,title:'',description:'',startsAt:'',endsAt:'',location:'',meetingUrl:'',pinned:false});
 const [editing,setEditing]=useState<string|null>(null);
 const load=async()=>{try{const [ss,cs,ts,ev]=await Promise.all([listCrossClassSchedules(),listClasses(),listAllAssignments(),listAllClassEvents()]);setItems(ss);setClasses(cs);setTasks(ts);setEvents(ev);const permissionEntries=await Promise.all(cs.map(async c=>[c.id,hasCapability((await getClassPosition(c.id))?.position??null,'manage_secretary')] as const));const permissions=Object.fromEntries(permissionEntries);setManageByClass(permissions);setCanManage(Boolean(permissions[activeClass]));}catch(e){setError(e instanceof Error?e.message:'Gagal memuat kalender.')}};
 useEffect(()=>{void listClasses().then(cs=>{setClasses(cs);const stored=getActiveClassId();const preferred=cs.find(c=>c.id===stored)?.id||cs[0]?.id||'';if(preferred){setActiveClass(preferred);setActiveClassId(preferred);}}).catch(()=>{});},[]);
 useEffect(()=>{void load()},[activeClass]);
 const localDateTime=(iso:string)=>{const d=new Date(iso);const pad=(n:number)=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`};
 const selectedDayNumber = new Date(`${selectedDate}T00:00:00`).getDay();
 const selectedWeekday = selectedDayNumber === 0 ? 7 : selectedDayNumber;
 const grouped=useMemo(()=>{const effectiveDay=day==='all'?String(selectedWeekday):day;const source=items.filter(x=>String(x.day_of_week)===effectiveDay);return days.slice(1).map((name,index)=>({name,day:index+1,items:source.filter(x=>x.day_of_week===index+1)})).filter(x=>day==='all'?x.day===selectedWeekday:String(x.day)===day)},[items,day,selectedWeekday]);
 const upcomingTasks=useMemo(()=>tasks.filter(t=>t.deadline&&t.progress_status!=='completed').sort((a,b)=>new Date(a.deadline!).getTime()-new Date(b.deadline!).getTime()).slice(0,6),[tasks]);
 const reset=()=>{setEditing(null);setForm({type:'presentation',title:'',description:'',startsAt:'',endsAt:'',location:'',meetingUrl:'',pinned:false})};
 const save=async(e:FormEvent)=>{e.preventDefault();if(!activeClass||!form.title.trim()||!form.startsAt)return;setError('');try{if(editing)await updateClassEvent(editing,{event_type:form.type,title:form.title,description:form.description,starts_at:new Date(form.startsAt).toISOString(),ends_at:form.endsAt?new Date(form.endsAt).toISOString():null,location:form.location,meeting_url:form.meetingUrl,pinned:form.pinned});else await createClassEvent(activeClass,{eventType:form.type,title:form.title,description:form.description,startsAt:new Date(form.startsAt).toISOString(),endsAt:form.endsAt?new Date(form.endsAt).toISOString():null,location:form.location,meetingUrl:form.meetingUrl,pinned:form.pinned});reset();await load();showToast(editing?'Event diperbarui.':'Event ditambahkan.','good')}catch(e){setError(e instanceof Error?e.message:'Gagal menyimpan event.')}};
 const remove=async(id:string)=>{if(!await requestConfirm('Hapus event ini?',{title:'Hapus event',confirmLabel:'Hapus'}))return;try{await deleteClassEvent(id);await load();showToast('Event dihapus.','good')}catch(e){setError(e instanceof Error?e.message:'Gagal menghapus event.')}};
 const startEdit=(e:ClassEvent)=>{setEditing(e.id);setActiveClass(e.class_id);setForm({type:e.event_type,title:e.title,description:e.description??'',startsAt:localDateTime(e.starts_at),endsAt:e.ends_at?localDateTime(e.ends_at):'',location:e.location??'',meetingUrl:e.meeting_url??'',pinned:e.pinned})};
 const normalizedFilter=(kind:'schedule'|'event'|'task')=>filter==='all'||filter===kind;
 const month=useMemo(()=>{const now=new Date();const year=now.getFullYear(),month=now.getMonth();const first=new Date(year,month,1);const offset=(first.getDay()+6)%7;const total=new Date(year,month+1,0).getDate();const daysArr:number[]=[];for(let i=0;i<offset;i++)daysArr.push(0);for(let d=1;d<=total;d++)daysArr.push(d);while(daysArr.length%7)daysArr.push(0);const eventDays=new Set(events.map(e=>{const d=new Date(e.starts_at);return d.getFullYear()===year&&d.getMonth()===month?d.getDate():-1}));return {year,month,days:daysArr,eventDays,today:now.getDate()};},[events]);
 const selectedEvents = useMemo(()=>events.filter(e=>new Date(e.starts_at).toLocaleDateString('sv-SE')===selectedDate),[events,selectedDate]);
 const monthLabel=new Intl.DateTimeFormat('id-ID',{month:'long',year:'numeric'}).format(new Date(month.year,month.month,1));
 return <div className="stack-page">
   <div className="page-title"><div><span className="eyebrow">Unified calendar</span><h2>Jadwal</h2><p>Kuliah, tugas, presentasi, ujian, rapat, dan event kelas dalam satu timeline.</p></div><div className="page-title-actions"><Button variant="soft" onClick={()=>activeClass&&openClassModule(activeClass,'/randomizer')}>🎡 Randomizer</Button><select value={day} onChange={e=>setDay(e.target.value)}><option value="all">Semua hari</option>{days.slice(1).map((d,i)=><option key={d} value={i+1}>{d}</option>)}</select></div></div>
   {error&&<div className="alert alert-danger" role="alert">{error}</div>}
   <Card className="month-card"><div className="section-head"><div><span className="eyebrow">Kalender</span><h3>{monthLabel}</h3></div><div className="button-row calendar-date-meta"><Badge tone="info">Hari ini · {month.today}</Badge><Badge tone="neutral">Dipilih · {new Intl.DateTimeFormat('id-ID',{day:'numeric',month:'short'}).format(new Date(`${selectedDate}T00:00:00`))}</Badge></div></div><div className="month-grid" aria-label={`Kalender ${monthLabel}`}>{['Sen','Sel','Rab','Kam','Jum','Sab','Min'].map(d=><button className="weekday" key={d} type="button" tabIndex={-1}>{d}</button>)}{month.days.map((d,i)=>d===0?<span key={`empty-${i}`} aria-hidden="true"/>:<button type="button" aria-pressed={selectedDate===`${month.year}-${String(month.month+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`} key={d} className={`${d===month.today?'today ':''}${month.eventDays.has(d)?'event-day ':''}${selectedDate===`${month.year}-${String(month.month+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`?'selected-day':''}`} onClick={()=>{const dayName=['','Senin','Selasa','Rabu','Kamis','Jumat','Sabtu','Minggu'][(new Date(month.year,month.month,d).getDay()+6)%7+1]; setSelectedDate(`${month.year}-${String(month.month+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`); setDay(String(((new Date(month.year,month.month,d).getDay()+6)%7)+1)); void dayName; }}>{d}</button>)}</div></Card>
   <div className="segmented calendar-filter"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>Semua</button><button className={filter==='schedule'?'active':''} onClick={()=>setFilter('schedule')}>Kuliah</button><button className={filter==='task'?'active':''} onClick={()=>setFilter('task')}>Tugas</button><button className={filter==='event'?'active':''} onClick={()=>setFilter('event')}>Event</button></div>
   {canManage&&<Card><div className="section-head"><div><span className="eyebrow">Class event</span><h3>{editing?'Edit event':'Tambah event kelas'}</h3></div><Badge tone="info">{activeClass?classes.find(c=>c.id===activeClass)?.name:'Kelas'}</Badge></div><form className="grid-form" onSubmit={save}><Field label="Kelas"><select value={activeClass} onChange={e=>{setActiveClass(e.target.value);setCanManage(Boolean(manageByClass[e.target.value]));}}>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Jenis"><select value={form.type} onChange={e=>setForm({...form,type:e.target.value as ClassEventType})}>{Object.entries(typeLabel).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><Field label="Judul"><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field label="Mulai"><input required type="datetime-local" value={form.startsAt} onChange={e=>setForm({...form,startsAt:e.target.value})}/></Field><Field label="Selesai"><input type="datetime-local" value={form.endsAt} onChange={e=>setForm({...form,endsAt:e.target.value})}/></Field><Field label="Lokasi"><input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></Field><Field label="Meeting URL"><input type="url" value={form.meetingUrl} onChange={e=>setForm({...form,meetingUrl:e.target.value})}/></Field><div className="span-2"><Field label="Deskripsi"><textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field></div><label className="checkbox-field"><input type="checkbox" checked={form.pinned} onChange={e=>setForm({...form,pinned:e.target.checked})}/> Pin event di kalender</label><div className="form-actions"><Button disabled={!activeClass}>{editing?'Simpan perubahan':'Tambah event'}</Button>{editing&&<Button type="button" variant="ghost" onClick={reset}>Batal</Button>}</div></form></Card>}
   {normalizedFilter('event')&&<Card><div className="section-head"><div><span className="eyebrow">Class events</span><h3>Event {new Intl.DateTimeFormat('id-ID',{day:'numeric',month:'short'}).format(new Date(`${selectedDate}T00:00:00`))}</h3></div></div>{selectedEvents.length?selectedEvents.map(e=><div className="calendar-event-row" key={e.id}><span className="calendar-event-icon">{typeIcon[e.event_type]}</span><div><div className="notification-title"><strong>{e.title}</strong>{e.pinned&&<Badge tone="info">Pinned</Badge>}</div><small>{typeLabel[e.event_type]} · {e.class_name||'Kelas'} · {new Date(e.starts_at).toLocaleString('id-ID')}{e.location?` · ${e.location}`:''}</small><p className="muted">{e.description||'Tidak ada deskripsi.'}</p>{e.meeting_url&&<a href={e.meeting_url} target="_blank" rel="noreferrer">Gabung meeting →</a>}</div>{Boolean(manageByClass[e.class_id])&&<div className="row-actions"><Button variant="ghost" onClick={()=>startEdit(e)}>Edit</Button><Button variant="danger" onClick={()=>void remove(e.id)}>Hapus</Button></div>}</div>):<Empty title="Tidak ada event di tanggal ini" body="Pilih tanggal lain atau buat presentasi, rapat, ujian, dan kegiatan kelas."/>}</Card>}
   {normalizedFilter('schedule')&&<div className="calendar-grid">{grouped.map(g=><Card key={g.day}><div className="section-head"><div><span className="eyebrow">{g.name}</span><h3>{g.items.length} sesi</h3></div></div>{g.items.length?g.items.map(s=><div key={s.id} className="schedule-mini"><Badge tone="info">{s.starts_at.slice(0,5)}–{s.ends_at.slice(0,5)}</Badge><div><strong>{s.subject?.name||'Mata kuliah'}</strong><small>{s.class_name||'Kelas'}{s.room?` · ${s.room}`:''}</small></div></div>):<Empty title="Kosong"/>}</Card>)}</div>}
   {normalizedFilter('task')&&<Card><div className="section-head"><div><span className="eyebrow">Deadlines</span><h3>Tugas yang mendekat</h3></div><Button variant="ghost" onClick={()=>activeClass&&openClassModule(activeClass,`/classes/${activeClass}?tab=tasks`)}>Lihat tugas</Button></div>{upcomingTasks.length?upcomingTasks.map(t=><div className="calendar-event-row" key={t.id}><span className="calendar-event-icon">⏰</span><div><strong>{t.title}</strong><small>{t.subject_name||'Tugas'} · {t.class_name||'Kelas'} · deadline {new Date(t.deadline!).toLocaleString('id-ID')}</small></div><Badge tone={t.priority==='urgent'||t.priority==='high'?'warn':'neutral'}>{t.priority}</Badge></div>):<Empty title="Tidak ada deadline dekat"/>}</Card>}
 </div>;
}
