import { useEffect, useMemo, useState } from 'react';
import { Badge, Card, Empty } from '../components/ui';
import { listClasses, listMyClassPositions } from '../lib/repository';
import { nav, setActiveClassId } from '../lib/router';
import type { ClassPositionRecord, ClassRecord } from '../types/models';
import { POSITION_LABEL } from '../lib/permissions';

export function ClassesPage(){
 const [classes,setClasses]=useState<ClassRecord[]>([]);const [positions,setPositions]=useState<Record<string,ClassPositionRecord|null>>({});const [error,setError]=useState('');const [query,setQuery]=useState('');const [semesterFilter,setSemesterFilter]=useState<'all'|'3'>('all');
 const visibleClasses=useMemo(()=>classes.filter(c=>{const q=query.trim().toLowerCase();const matches=!q||c.name.toLowerCase().includes(q)||(c.study_program||'').toLowerCase().includes(q)||(c.class_code||'').toLowerCase().includes(q);const semesterOk=semesterFilter==='all'||String(c.semester||'')==='3';return matches&&semesterOk}),[classes,query,semesterFilter]);
 useEffect(()=>{(async()=>{try{const [cs,ps]=await Promise.all([listClasses(),listMyClassPositions()]);setClasses(cs);setPositions(Object.fromEntries(ps.map(p=>[p.class_id,p])));}catch(e){setError(e instanceof Error?e.message:'Gagal memuat kelas.')}})()},[]);
 return <div className="stack-page"><div className="classes-desktop-reference"><div className="page-title"><div><span className="eyebrow">Workspace</span><h2>Kelas saya</h2><p>Kelas ditetapkan oleh pengelola sistem. Tidak ada aksi pembuatan atau keanggotaan mandiri dari aplikasi.</p></div></div></div><div className="classes-mobile-reference"><div className="mobile-page-head"><button className="mobile-back" onClick={()=>nav('/dashboard')} aria-label="Kembali">‹</button><div><h2>Kelas</h2><small>{classes.length} kelas aktif</small></div><button className="mobile-head-icon" onClick={()=>nav('/search')} aria-label="Cari">⌕</button></div><label className="mobile-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari kelas…"/><b>{query?`${visibleClasses.length}`:''}</b></label><div className="mobile-pills"><button className={semesterFilter==='all'?'active':''} onClick={()=>setSemesterFilter('all')}>Semua</button><button className={semesterFilter==='3'?'active':''} onClick={()=>setSemesterFilter('3')}>Semester 3</button></div>{error&&<div className="alert alert-danger">{error}</div>}<div className="mobile-class-list">{visibleClasses.length?visibleClasses.map(c=>{const p=positions[c.id];return <button className="mobile-class-row" key={c.id} onClick={()=>{setActiveClassId(c.id);nav(`/classes/${c.id}`)}}><span className={`mobile-class-icon ${c.name.includes('15')?'purple':''}`}>▣</span><span><strong>{c.name}</strong><small>{c.study_program||'Sistem Informasi'}</small><small>{c.semester?`Semester ${c.semester}`:'Semester'} · Buka untuk melihat modul</small></span><b className="chevron">›</b></button>}) : <Empty title="Belum ada kelas" body="Hubungi pengelola sistem untuk penempatan kelas."/>}</div></div><div className="class-grid">{visibleClasses.length?visibleClasses.map(c=>{const p=positions[c.id];return <button className="class-card" key={c.id} onClick={()=>{setActiveClassId(c.id);nav(`/classes/${c.id}`)}}><div className="class-card-top"><span className="class-mark">{c.name.charAt(0)}</span><Badge tone={p?'info':'neutral'}>{p?POSITION_LABEL[p.position]:'Anggota'}</Badge></div><div><strong>{c.name}</strong><p>{c.study_program||'Program studi'} · Semester {c.semester??'-'}</p></div><div className="class-meta"><span>{c.academic_year||'Tahun akademik —'}</span><span>{c.delivery_mode==='online'?'🌐 Online':'📍 Offline'}</span></div></button>}) : <Empty title="Belum ada kelas yang ditetapkan" body="Hubungi pengelola sistem untuk memasukkan akunmu ke kelas yang benar."/>}</div><Card className="classes-access-card"><div className="section-head"><div><span className="eyebrow">Aturan akses</span><h3>Kelas dikelola secara terpusat</h3></div></div><p className="muted">Pengguna tidak dapat mengelola keanggotaan kelas secara mandiri atau membuka direktori anggota. Penempatan akun dan jabatan diatur oleh pimpinan/pengelola kelas melalui sistem.</p></Card></div>
}
