import { useEffect, useState, type FormEvent } from 'react';
import { Button, Card, Empty, Field } from '../components/ui';
import { listClasses, listNotes, listSharedNotes, saveNote } from '../lib/repository';
import type { ClassRecord, PersonalNote, SharedNote } from '../types/models';
import { getActiveClassId, nav, openClassModule, setActiveClassId } from '../lib/router';
import { showToast } from '../components/ToastHost';

export function NotesPage(){
 const [tab,setTab]=useState<'personal'|'shared'>('personal');
 const [items,setItems]=useState<PersonalNote[]>([]);const [shared,setShared]=useState<SharedNote[]>([]);const [classes,setClasses]=useState<ClassRecord[]>([]);const [activeClass,setActiveClass]=useState('');
 const [error,setError]=useState('');const [title,setTitle]=useState('');const [content,setContent]=useState('');const [noteClass,setNoteClass]=useState<string>('');const [editing,setEditing]=useState<string|null>(null);
 useEffect(()=>{Promise.all([listClasses(),listNotes()]).then(async([cs,ns])=>{setClasses(cs);setItems(ns);const stored=getActiveClassId();const preferred=cs.find(c=>c.id===stored)?.id||cs[0]?.id;if(preferred){setActiveClass(preferred);setActiveClassId(preferred);try{setShared(await listSharedNotes(cs[0].id))}catch{}}}).catch(e=>setError(e instanceof Error?e.message:'Gagal memuat catatan.'))},[]);
 useEffect(()=>{if(tab==='shared'&&activeClass)void listSharedNotes(activeClass).then(setShared).catch(()=>setShared([]))},[tab,activeClass]);
 const submit=async(e:FormEvent)=>{e.preventDefault();setError('');try{const n=await saveNote({id:editing??undefined,classId:noteClass||null,title,content,pinned:false});setItems(prev=>editing?prev.map(x=>x.id===editing?n:x):[n,...prev]);showToast(editing?'Catatan diperbarui.':'Catatan tersimpan.','good');setTitle('');setContent('');setEditing(null)}catch(e){setError(e instanceof Error?e.message:'Gagal menyimpan catatan.')}};
 const edit=(n:PersonalNote)=>{setTab('personal');setEditing(n.id);setTitle(n.title);setContent(n.content);setNoteClass(n.class_id??'')};
 return <div className="stack-page">
  {error&&<div className="alert alert-danger" role="alert">{error}</div>}
  <div className="page-title"><div><span className="eyebrow">Private workspace</span><h2>Catatan</h2><p>Catatan pribadi tetap milikmu; catatan bersama mengikuti workspace kelas.</p></div></div>
  <div className="reference-chip-row"><button className={`reference-chip ${tab==='personal'?'active':''}`} onClick={()=>setTab('personal')}>Pribadi</button><button className={`reference-chip ${tab==='shared'?'active':''}`} onClick={()=>setTab('shared')}>Bersama</button></div>
  {tab==='personal'?<div className="grid-2"><Card><h3>{editing?'Edit catatan':'Catatan baru'}</h3><form onSubmit={submit} className="stack-form"><Field label="Judul"><input value={title} onChange={e=>setTitle(e.target.value)} required placeholder="Judul catatan"/></Field><Field label="Kelas (opsional)"><select value={noteClass} onChange={e=>setNoteClass(e.target.value)}><option value="">Semua / pribadi</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Isi"><textarea rows={10} value={content} onChange={e=>setContent(e.target.value)} placeholder="Tulis catatan…"/></Field><div className="form-actions"><Button type="submit">{editing?'Simpan perubahan':'Simpan catatan'}</Button>{editing&&<Button type="button" variant="ghost" onClick={()=>{setEditing(null);setTitle('');setContent('')}}>Batal</Button>}</div></form></Card><Card><div className="section-head"><div><span className="eyebrow">Saved</span><h3>Catatan tersimpan</h3></div></div>{items.length?items.map(n=><button className="note-card" key={n.id} onClick={()=>edit(n)}><strong>{n.title}</strong><span>{n.content.slice(0,140)}</span><small>{new Date(n.updated_at).toLocaleString('id-ID')}</small></button>):<Empty title="Belum ada catatan"/>}</Card></div>:<Card><div className="section-head"><div><span className="eyebrow">Class workspace</span><h3>Catatan bersama</h3></div></div><div className="filter-bar"><select value={activeClass} onChange={e=>{setActiveClass(e.target.value);setActiveClassId(e.target.value)}}>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div>{shared.length?shared.map(n=><div className="note-card" key={n.id}><strong>{n.title}</strong><span>{n.content.slice(0,180)}</span><small>v{n.version} · {new Date(n.updated_at).toLocaleString('id-ID')}</small></div>):<Empty title="Belum ada catatan bersama" body="Buka workspace kelas untuk membuat atau memperbarui catatan bersama."/>}<Button variant="soft" onClick={()=>activeClass&&openClassModule(activeClass,`/classes/${activeClass}?tab=shared-notes`)}>Buka workspace kelas</Button></Card>}
 </div>;
}
