import { getActiveClassId, setActiveClassId } from '../lib/router';
import { useEffect, useMemo, useState } from 'react';
import { Badge, Button, Card, Empty } from '../components/ui';
import { assignClassPosition, getClassPosition, listClassMembers, listClassPositions, listClasses, removeClassPosition } from '../lib/repository';
import type { ClassMember, ClassPosition, ClassPositionRecord, ClassRecord } from '../types/models';
import { hasCapability, POSITION_DESCRIPTION, POSITION_LABEL } from '../lib/permissions';

const offices: ClassPosition[] = ['ketua','wakil_ketua','sekretaris','bendahara'];
export function PositionsPage(){
 const [classes,setClasses]=useState<ClassRecord[]>([]);const [active,setActive]=useState('');const [mine,setMine]=useState<ClassPositionRecord|null>(null);const [positions,setPositions]=useState<ClassPositionRecord[]>([]);const [members,setMembers]=useState<ClassMember[]>([]);const [selectedOffice,setSelectedOffice]=useState<ClassPosition>('sekretaris');const [selectedUser,setSelectedUser]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const canManage=useMemo(()=>hasCapability(mine?.position??null,'manage_class'),[mine]);
 const load=async()=>{if(!active)return;try{const [m,p,ms]=await Promise.all([getClassPosition(active),listClassPositions(active),listClassMembers(active)]);setMine(m);setPositions(p);setMembers(ms);}catch(e){setError(e instanceof Error?e.message:'Gagal memuat jabatan.')}};
 useEffect(()=>{listClasses().then(cs=>{setClasses(cs);if(cs[0]){const preferred=cs.find(c=>c.id===getActiveClassId())?.id||cs[0].id;setActive(preferred);setActiveClassId(preferred);}}).catch(e=>setError(e instanceof Error?e.message:'Gagal memuat kelas.'))},[]);
 useEffect(()=>{void load()},[active]);
 const assign=async()=>{if(!active||!selectedUser)return;setBusy(true);setError('');try{await assignClassPosition(active,selectedUser,selectedOffice);await load();setSelectedUser('')}catch(e){setError(e instanceof Error?e.message:'Gagal menetapkan jabatan.')}finally{setBusy(false)}};
 const remove=async(uid:string)=>{if(!active)return;setBusy(true);try{await removeClassPosition(active,uid);await load()}catch(e){setError(e instanceof Error?e.message:'Gagal melepas jabatan.')}finally{setBusy(false)}};
 return <div className="stack-page"><div className="page-title"><div><span className="eyebrow">Class officers</span><h2>Jabatan Kelas</h2><p>Pengaturan hak akses berdasarkan jabatan, bukan berdasarkan menu admin/member umum.</p></div><div className="page-title-actions"><button className="link-btn" onClick={()=>{if(active)location.hash=`#/classes/${active}`}}>← Workspace</button><Badge tone={canManage?'info':'neutral'}>{mine?.position?POSITION_LABEL[mine.position]:'Anggota'}</Badge></div></div>{error&&<div className="alert alert-danger">{error}</div>}<div className="filter-bar"><select value={active} onChange={e=>{setActive(e.target.value);setActiveClassId(e.target.value)}}>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="position-grid">{offices.map(office=>{const row=positions.find(p=>p.position===office);return <Card key={office}><div className="section-head"><div><span className="eyebrow">{POSITION_LABEL[office]}</span><h3>{row?.full_name||'Belum ditetapkan'}</h3></div>{row&&<Badge tone="good">Aktif</Badge>}</div><p className="muted">{POSITION_DESCRIPTION[office]}</p>{canManage&&row&&<Button variant="ghost" onClick={()=>void remove(row.user_id)} disabled={busy}>Lepas jabatan</Button>}</Card>})}</div>{canManage&&<Card><div className="section-head"><div><span className="eyebrow">Assignment</span><h3>Tetapkan jabatan</h3></div></div><div className="grid-form"><label className="field"><span>Jabatan</span><select value={selectedOffice} onChange={e=>setSelectedOffice(e.target.value as ClassPosition)}>{offices.map(o=><option key={o} value={o}>{POSITION_LABEL[o]}</option>)}</select></label><label className="field"><span>Mahasiswa</span><select value={selectedUser} onChange={e=>setSelectedUser(e.target.value)}><option value="">Pilih mahasiswa</option>{members.filter(m=>m.status==='active').map(m=><option key={m.user_id} value={m.user_id}>{m.full_name||m.user_id}{m.nim?` — ${m.nim}`:''}</option>)}</select></label><div className="form-actions"><Button disabled={busy||!selectedUser} onClick={()=>void assign()}>{busy?'Menyimpan…':'Tetapkan jabatan'}</Button></div></div><div className="alert alert-info">Halaman ini bukan direktori anggota. Daftar mahasiswa hanya digunakan secara internal ketika pimpinan menetapkan jabatan.</div></Card>} {!positions.length&&<Empty title="Belum ada struktur jabatan" body="Pimpinan kelas dapat menetapkan ketua, wakil, sekretaris, dan bendahara."/>}</div>
}
