-- Student Hub v1.1.0 Phase 3: server sync cursor and bounded change feed.
CREATE TABLE IF NOT EXISTS public.sync_events (
  cursor bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name text NOT NULL,
  entity_id uuid,
  class_id uuid,
  user_id uuid,
  changed_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS sync_events_cursor_idx ON public.sync_events(cursor);
CREATE INDEX IF NOT EXISTS sync_events_class_idx ON public.sync_events(class_id,cursor);
CREATE INDEX IF NOT EXISTS sync_events_user_idx ON public.sync_events(user_id,cursor);
ALTER TABLE public.sync_events ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.sync_event_class_id(p_table text,p_entity uuid,p_class_id uuid,p_user_id uuid)
RETURNS uuid
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public,private
AS $$
DECLARE v uuid;
BEGIN
  IF p_class_id IS NOT NULL THEN RETURN p_class_id; END IF;
  CASE p_table
    WHEN 'classes' THEN SELECT id INTO v FROM public.classes WHERE id=p_entity;
    WHEN 'subjects' THEN SELECT class_id INTO v FROM public.subjects WHERE id=p_entity;
    WHEN 'schedules' THEN SELECT s.class_id INTO v FROM public.schedules sc JOIN public.subjects s ON s.id=sc.subject_id WHERE sc.id=p_entity;
    WHEN 'assignments' THEN SELECT class_id INTO v FROM public.assignments WHERE id=p_entity;
    WHEN 'assignment_progress' THEN SELECT a.class_id INTO v FROM public.assignment_progress ap JOIN public.assignments a ON a.id=ap.assignment_id WHERE ap.id=p_entity;
    WHEN 'assignment_checklist_items' THEN SELECT a.class_id INTO v FROM public.assignment_checklist_items ci JOIN public.assignments a ON a.id=ci.assignment_id WHERE ci.id=p_entity;
    WHEN 'checklist_progress' THEN SELECT a.class_id INTO v FROM public.checklist_progress cp JOIN public.assignment_checklist_items ci ON ci.id=cp.checklist_item_id JOIN public.assignments a ON a.id=ci.assignment_id WHERE cp.id=p_entity;
    WHEN 'materials' THEN SELECT class_id INTO v FROM public.materials WHERE id=p_entity;
    WHEN 'assignment_files' THEN SELECT a.class_id INTO v FROM public.assignment_files af JOIN public.assignments a ON a.id=af.assignment_id WHERE af.file_id=p_entity LIMIT 1;
    WHEN 'material_files' THEN SELECT m.class_id INTO v FROM public.material_files mf JOIN public.materials m ON m.id=mf.material_id WHERE mf.file_id=p_entity LIMIT 1;
    WHEN 'files' THEN SELECT class_id INTO v FROM public.files WHERE id=p_entity;
    WHEN 'announcements' THEN SELECT class_id INTO v FROM public.announcements WHERE id=p_entity;
    WHEN 'announcement_reads' THEN SELECT a.class_id INTO v FROM public.announcement_reads ar JOIN public.announcements a ON a.id=ar.announcement_id WHERE ar.id=p_entity;
    WHEN 'forum_topics' THEN SELECT class_id INTO v FROM public.forum_topics WHERE id=p_entity;
    WHEN 'forum_posts' THEN SELECT t.class_id INTO v FROM public.forum_posts fp JOIN public.forum_topics t ON t.id=fp.topic_id WHERE fp.id=p_entity;
    WHEN 'forum_reports' THEN SELECT t.class_id INTO v FROM public.forum_reports fr JOIN public.forum_topics t ON t.id=fr.topic_id WHERE fr.id=p_entity;
    WHEN 'forum_post_files' THEN SELECT t.class_id INTO v FROM public.forum_post_files fpf JOIN public.forum_posts fp ON fp.id=fpf.post_id JOIN public.forum_topics t ON t.id=fp.topic_id WHERE fpf.file_id=p_entity LIMIT 1;
    WHEN 'forum_post_files' THEN SELECT t.class_id INTO v FROM public.forum_post_files fpf JOIN public.forum_posts fp ON fp.id=fpf.post_id JOIN public.forum_topics t ON t.id=fp.topic_id WHERE fpf.file_id=p_entity LIMIT 1;
    WHEN 'groups' THEN SELECT class_id INTO v FROM public.groups WHERE id=p_entity;
    WHEN 'group_members' THEN SELECT g.class_id INTO v FROM public.group_members gm JOIN public.groups g ON g.id=gm.group_id WHERE gm.id=p_entity;
    WHEN 'group_tasks' THEN SELECT g.class_id INTO v FROM public.group_tasks gt JOIN public.groups g ON g.id=gt.group_id WHERE gt.id=p_entity;
    WHEN 'polls' THEN SELECT class_id INTO v FROM public.polls WHERE id=p_entity;
    WHEN 'poll_options' THEN SELECT p.class_id INTO v FROM public.poll_options po JOIN public.polls p ON p.id=po.poll_id WHERE po.id=p_entity;
    WHEN 'poll_votes' THEN SELECT p.class_id INTO v FROM public.poll_votes pv JOIN public.polls p ON p.id=pv.poll_id WHERE pv.id=p_entity;
    WHEN 'cash_accounts' THEN SELECT class_id INTO v FROM public.cash_accounts WHERE id=p_entity;
    WHEN 'cash_transactions' THEN SELECT ca.class_id INTO v FROM public.cash_transactions ct JOIN public.cash_accounts ca ON ca.id=ct.cash_account_id WHERE ct.id=p_entity;
    WHEN 'cash_dues' THEN SELECT class_id INTO v FROM public.cash_dues WHERE id=p_entity;
    WHEN 'cash_payments' THEN SELECT d.class_id INTO v FROM public.cash_payments cp JOIN public.cash_dues d ON d.id=cp.due_id WHERE cp.id=p_entity;
    WHEN 'shared_notes' THEN SELECT class_id INTO v FROM public.shared_notes WHERE id=p_entity;
    WHEN 'class_admin_notes' THEN SELECT class_id INTO v FROM public.class_admin_notes WHERE id=p_entity;
    WHEN 'albums' THEN SELECT class_id INTO v FROM public.albums WHERE id=p_entity;
    WHEN 'photos' THEN SELECT a.class_id INTO v FROM public.photos ph JOIN public.albums a ON a.id=ph.album_id WHERE ph.id=p_entity;
    WHEN 'class_members' THEN SELECT class_id INTO v FROM public.class_members WHERE id=p_entity;
    WHEN 'class_positions' THEN SELECT class_id INTO v FROM public.class_positions WHERE id=p_entity;
    ELSE NULL;
  END CASE;
  RETURN v;
END;
$$;

CREATE OR REPLACE FUNCTION public.capture_sync_event()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,private
AS $$
DECLARE
  v_new jsonb := CASE WHEN TG_OP = 'DELETE' THEN '{}'::jsonb ELSE to_jsonb(NEW) END;
  v_old jsonb := CASE WHEN TG_OP = 'INSERT' THEN '{}'::jsonb ELSE to_jsonb(OLD) END;
  v_id uuid; v_class uuid; v_user uuid;
BEGIN
  v_id := COALESCE(NULLIF(v_new->>'id','')::uuid, NULLIF(v_old->>'id','')::uuid);
  v_class := COALESCE(NULLIF(v_new->>'class_id','')::uuid, NULLIF(v_old->>'class_id','')::uuid);
  v_user := COALESCE(NULLIF(v_new->>'user_id','')::uuid, NULLIF(v_old->>'user_id','')::uuid);
  IF v_id IS NULL THEN
    v_id := COALESCE(NULLIF(v_new->>'file_id','')::uuid, NULLIF(v_old->>'file_id','')::uuid);
  END IF;
  IF v_id IS NULL THEN
    v_id := COALESCE(NULLIF(v_new->>'post_id','')::uuid, NULLIF(v_old->>'post_id','')::uuid);
  END IF;
  IF v_id IS NULL THEN
    v_id := COALESCE(NULLIF(v_new->>'material_id','')::uuid, NULLIF(v_old->>'material_id','')::uuid);
  END IF;
  IF v_id IS NULL THEN
    v_id := COALESCE(NULLIF(v_new->>'announcement_id','')::uuid, NULLIF(v_old->>'announcement_id','')::uuid);
  END IF;
  IF v_id IS NULL THEN
    v_id := COALESCE(NULLIF(v_new->>'assignment_id','')::uuid, NULLIF(v_old->>'assignment_id','')::uuid);
  END IF;
  IF v_id IS NULL THEN
    v_id := COALESCE(NULLIF(v_new->>'group_id','')::uuid, NULLIF(v_old->>'group_id','')::uuid);
  END IF;
  IF v_id IS NULL THEN
    v_id := COALESCE(NULLIF(v_new->>'poll_id','')::uuid, NULLIF(v_old->>'poll_id','')::uuid);
  END IF;
  v_class := public.sync_event_class_id(TG_TABLE_NAME,v_id,v_class,v_user);
  INSERT INTO public.sync_events(table_name,entity_id,class_id,user_id) VALUES (TG_TABLE_NAME,v_id,v_class,v_user);
  RETURN COALESCE(NEW,OLD);
END;
$$;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'classes','class_members','class_positions','subjects','schedules','assignments','assignment_progress','assignment_checklist_items','checklist_progress','materials','material_files','files','announcements','announcement_reads','forum_topics','forum_posts','forum_post_files','groups','group_members','group_tasks','polls','poll_options','poll_votes','cash_accounts','cash_transactions','cash_dues','cash_payments','shared_notes','class_admin_notes','albums','photos','personal_notes','notifications'
  ] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS trg_sync_%I ON public.%I',t,t);
    EXECUTE format('CREATE TRIGGER trg_sync_%I AFTER INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.capture_sync_event()',t,t);
  END LOOP;
END $$;

CREATE OR REPLACE FUNCTION public.pull_sync_events(p_cursor bigint DEFAULT 0,p_limit integer DEFAULT 100)
RETURNS TABLE(next_cursor bigint,table_name text,entity_id uuid,changed_at timestamptz)
LANGUAGE sql SECURITY DEFINER SET search_path=public,private
AS $$
  SELECT e.cursor,e.table_name,e.entity_id,e.changed_at
  FROM public.sync_events e
  WHERE e.cursor>COALESCE(p_cursor,0)
    AND (
      (e.user_id IS NOT NULL AND e.user_id=auth.uid())
      OR (e.class_id IS NOT NULL AND public.is_class_member(e.class_id))
    )
  ORDER BY e.cursor
  LIMIT LEAST(GREATEST(COALESCE(p_limit,100),1),500);
$$;
REVOKE ALL ON FUNCTION public.pull_sync_events(bigint,integer) FROM public,anon;
GRANT EXECUTE ON FUNCTION public.pull_sync_events(bigint,integer) TO authenticated;
