-- Student Hub v1.2.0 — class productivity, calendar events, decisions and trusted activity timeline.
-- Intentionally adds no attendance, lecturer, create-class, or join-class UI/workflow.

ALTER TABLE public.polls
  ADD COLUMN IF NOT EXISTS is_decision boolean NOT NULL DEFAULT false;
CREATE INDEX IF NOT EXISTS polls_decision_idx ON public.polls(class_id, is_decision, created_at DESC) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS public.class_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  class_id uuid NOT NULL REFERENCES public.classes(id) ON DELETE CASCADE,
  created_by uuid NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  event_type text NOT NULL CHECK (event_type IN ('class','presentation','exam','meeting','task_deadline','other')),
  title text NOT NULL CHECK (char_length(trim(title)) BETWEEN 1 AND 200),
  description text,
  starts_at timestamptz NOT NULL,
  ends_at timestamptz,
  location text,
  meeting_url text,
  pinned boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CHECK (ends_at IS NULL OR ends_at >= starts_at)
);
CREATE INDEX IF NOT EXISTS class_events_class_start_idx ON public.class_events(class_id, starts_at) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS class_events_pinned_idx ON public.class_events(class_id, pinned, starts_at DESC) WHERE deleted_at IS NULL;
DROP TRIGGER IF EXISTS class_events_set_updated_at ON public.class_events;
CREATE TRIGGER class_events_set_updated_at
BEFORE UPDATE ON public.class_events
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.class_events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS class_events_select_member ON public.class_events;
CREATE POLICY class_events_select_member ON public.class_events
FOR SELECT TO authenticated
USING (public.is_class_member(class_id) AND deleted_at IS NULL);
DROP POLICY IF EXISTS class_events_insert_manager ON public.class_events;
CREATE POLICY class_events_insert_manager ON public.class_events
FOR INSERT TO authenticated
WITH CHECK (created_by = auth.uid() AND public.can_manage_secretary_features(class_id));
DROP POLICY IF EXISTS class_events_update_manager ON public.class_events;
CREATE POLICY class_events_update_manager ON public.class_events
FOR UPDATE TO authenticated
USING (public.can_manage_secretary_features(class_id))
WITH CHECK (public.can_manage_secretary_features(class_id));
DROP POLICY IF EXISTS class_events_delete_manager ON public.class_events;
CREATE POLICY class_events_delete_manager ON public.class_events
FOR DELETE TO authenticated
USING (public.can_manage_secretary_features(class_id));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.class_events TO authenticated;

-- Trusted activity timeline. Writes are generated by triggers rather than browser clients.
CREATE OR REPLACE FUNCTION public.log_class_activity()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, private
AS $$
DECLARE
  v_class uuid;
  v_user uuid;
  v_id uuid;
  v_action text;
BEGIN
  v_id := COALESCE(NEW.id, OLD.id);
  v_class := COALESCE(NEW.class_id, OLD.class_id);
  IF TG_TABLE_NAME = 'schedules' THEN
    SELECT s.class_id INTO v_class FROM public.schedules sc JOIN public.subjects s ON s.id = COALESCE(NEW.subject_id, OLD.subject_id) WHERE sc.id = COALESCE(NEW.id, OLD.id) LIMIT 1;
  ELSIF TG_TABLE_NAME = 'group_tasks' THEN
    SELECT g.class_id INTO v_class FROM public.groups g WHERE g.id = COALESCE(NEW.group_id, OLD.group_id);
  ELSIF TG_TABLE_NAME = 'cash_transactions' THEN
    SELECT ca.class_id INTO v_class FROM public.cash_accounts ca WHERE ca.id = COALESCE(NEW.cash_account_id, OLD.cash_account_id);
  ELSIF TG_TABLE_NAME = 'cash_payments' THEN
    SELECT d.class_id INTO v_class FROM public.cash_dues d WHERE d.id = COALESCE(NEW.due_id, OLD.due_id);
  ELSIF TG_TABLE_NAME = 'photos' THEN
    SELECT a.class_id INTO v_class FROM public.albums a WHERE a.id = COALESCE(NEW.album_id, OLD.album_id);
  END IF;
  v_user := COALESCE(
    NULLIF(to_jsonb(NEW)->>'created_by','')::uuid,
    NULLIF(to_jsonb(NEW)->>'user_id','')::uuid,
    NULLIF(to_jsonb(NEW)->>'uploaded_by','')::uuid,
    auth.uid()
  );
  v_action := TG_OP || ' ' || replace(TG_TABLE_NAME,'_',' ');
  IF v_class IS NOT NULL THEN
    INSERT INTO public.activity_logs(user_id,class_id,action,entity_type,entity_id,metadata)
    VALUES(v_user,v_class,v_action,TG_TABLE_NAME,v_id,jsonb_build_object('triggered_at',now()));
  END IF;
  RETURN COALESCE(NEW, OLD);
END;
$$;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'assignments','materials','announcements','forum_topics','forum_posts','groups','group_tasks',
    'polls','cash_transactions','cash_dues','cash_payments','albums','photos','class_events'
  ] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS trg_activity_%I ON public.%I',t,t);
    EXECUTE format('CREATE TRIGGER trg_activity_%I AFTER INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.log_class_activity()',t,t);
  END LOOP;
END $$;

-- Keep new event changes available to the incremental sync mechanism.
DROP TRIGGER IF EXISTS trg_sync_class_events ON public.class_events;
CREATE TRIGGER trg_sync_class_events
AFTER INSERT OR UPDATE OR DELETE ON public.class_events
FOR EACH ROW EXECUTE FUNCTION public.capture_sync_event();
